const TaskEnums = {
    INCREMENT: "INCREMENT",
    DOUBLE: "DOUBLE",
    DECREMENT: "DECREMENT",
    FALLBACK_FOR_DOUBLE: "FALLBACK_FOR_DOUBLE",
    DATA_INGESTION_MERGE: "DATA_INGESTION_MERGE",
    DAILY_AGGREGATION: "DAILY_AGGREGATION",
    TECHNICAL_ANALYSIS: "TECHNICAL_ANALYSIS",
    VISUALIZATION_PREPARATION: "VISUALIZATION_PREPARATION"
  };

  module.exports = TaskEnums