const TaskEnums = {
    INCREMENT: "INCREMENT",
    DOUBLE: "DOUBLE",
    DECREMENT: "DECREMENT",
    FALLBACK_FOR_DOUBLE: "FALLBACK_FOR_DOUBLE",
    OHLC: "OHLC",
    ARGSFN:"ARGSFN",
    VOLUME_SPIKE_DETECTOR: "VOLUME_SPIKE_DETECTOR"
  };

  module.exports = TaskEnums