const TaskEnums = {
    INCREMENT: "INCREMENT",
    DOUBLE: "DOUBLE",
    DECREMENT: "DECREMENT",
    FALLBACK_FOR_DOUBLE: "FALLBACK_FOR_DOUBLE",
    OHLC: "OHLC",
    ARGSFN:"ARGSFN",
    VOLUME_SPIKE_DETECTOR: "VOLUME_SPIKE_DETECTOR",
    SUDDEN_CORRELATION_SHIFT: "SUDDEN_CORRELATION_SHIFT"
  };

  module.exports = TaskEnums